title: Profile of Muhammad Omer Bin Tauqeer
author: Omer Bin tauqeer
email: omerbintauqeer@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# show_excerpts: true # set to true to show excerpts on the homepage


plainwhite:
#   name: Muhammad Omer Bin Tauqeer
  tagline: Researcher. Pentester. System Administrator
  date_format: "%b %-d, %Y"
  # sitemap: true # set to true to generate sitemap.xml content
  # search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image:  "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp

  tagline: |

    Researcher 
    Pentester 

#    # Third Line.

  navigation:
    # - title: My Work
    #   url: "/my-work"
    # - title: Resume
    #   url: "/resume"

  social_links:
    github: OmerTauqeer
    linkedIn: in/omer-tauqeer-6584b876 # format: locale/username

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- resume.md

# Build settings
theme: plainwhite
# remote_theme: samarsault/plainwhite-jekyll

plugins:
 - jekyll-seo-tag
 - jekyll-feed

